<a href="https://colab.research.google.com/github/hamzaboufikr/hamza/blob/master/Advanced%20Linear%20Regression%20With%20statsmodels.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import statsmodels.api as sm

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [0]:
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

In [0]:
x = sm.add_constant(x)
#That’s how you add the column of ones to x with add_constant(). 
#It takes the input array x as an argument and returns a new array with the column of ones inserted at the beginning.

In [4]:
print(x)
print(y)

[[ 1.  0.  1.]
 [ 1.  5.  1.]
 [ 1. 15.  2.]
 [ 1. 25.  5.]
 [ 1. 35. 11.]
 [ 1. 45. 15.]
 [ 1. 55. 34.]
 [ 1. 60. 35.]]
[ 4  5 20 14 32 22 38 43]


In [0]:
#Step 3: Create a model and fit it
model = sm.OLS(y, x)
#The regression model based on ordinary least squares is an instance of the class statsmodels.regression.linear_model.OLS.

In [0]:
results = model.fit()

In [7]:
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.862
Model:                            OLS   Adj. R-squared:                  0.806
Method:                 Least Squares   F-statistic:                     15.56
Date:                Mon, 25 May 2020   Prob (F-statistic):            0.00713
Time:                        00:25:02   Log-Likelihood:                -24.316
No. Observations:                   8   AIC:                             54.63
Df Residuals:                       5   BIC:                             54.87
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.5226      4.431      1.246      0.2

/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  "anyway, n=%i" % int(n))


In [8]:
print('coefficient of determination:', results.rsquared)
#.rsquared holds 𝑅².

coefficient of determination: 0.8615939258756776


In [9]:
print('adjusted coefficient of determination:', results.rsquared_adj)
#.rsquared_adj represents adjusted 𝑅² (𝑅² corrected according to the number of input features).

adjusted coefficient of determination: 0.8062314962259487


In [10]:
print('predicted response:', results.fittedvalues, sep='\n')

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [11]:
print('predicted response:', results.predict(x), sep='\n')
#This is the predicted response for known inputs. 

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [12]:
x_new = sm.add_constant(np.arange(10).reshape((-1, 2)))
print(x_new)

[[1. 0. 1.]
 [1. 2. 3.]
 [1. 4. 5.]
 [1. 6. 7.]
 [1. 8. 9.]]


In [13]:
#If you want predictions with new regressors, you can also apply .predict() with new data as the argument
y_new = results.predict(x_new)
print(y_new)

[ 5.77760476  7.18179502  8.58598528  9.99017554 11.3943658 ]
