<a href="https://colab.research.google.com/github/hamzaboufikr/hamza/blob/master/linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [0]:
x=np.array([5,15,25,35,45,55]).reshape((-1,1))
y=np.array([5,20,14,32,22,38])

In [3]:
print(x)
print(y)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]
[ 5 20 14 32 22 38]


In [4]:
model=LinearRegression()
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
model=LinearRegression().fit(x,y)
#la même chose que model=LinearRegression() + model.fit(x,y)

In [0]:
r_sq=model.score(x,y)

In [9]:
print('coefficient of determination: R²',r_sq)

coefficient of determination: R² 0.7158756137479542


In [11]:
print('intercept:',model.intercept_)
print('slope:',model.coef_)

intercept: 5.633333333333329
slope: [0.54]


In [12]:
y_pred=model.predict(x)
print('predicted response:',y_pred,sep='\n')

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [14]:
y_pred=model.intercept_+model.coef_*x
print('predicted response:',y_pred,sep='\n')

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


In [0]:
x_new = np.arange(5).reshape((-1, 1))
print(x_new)