<a href="https://colab.research.google.com/github/hamzaboufikr/hamza/blob/master/Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [0]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([15, 11, 2, 8, 25, 32])

In [0]:
transformer = PolynomialFeatures(degree=2, include_bias=False)

In [4]:
transformer.fit(x)

PolynomialFeatures(degree=2, include_bias=False, interaction_only=False,
                   order='C')

In [0]:
x_ = transformer.transform(x)

In [0]:
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

In [7]:
print(x_)

[[   5.   25.]
 [  15.  225.]
 [  25.  625.]
 [  35. 1225.]
 [  45. 2025.]
 [  55. 3025.]]


In [0]:
#Create a model and fit it
model = LinearRegression().fit(x_, y)

In [9]:
#You can obtain the properties of the model the same way as in the case of linear regression:
r_sq = model.score(x_, y)
print('coefficient of determination:', r_sq)
print('intercept:', model.intercept_)
print('coefficients:', model.coef_)

coefficient of determination: 0.8908516262498564
intercept: 21.37232142857144
coefficients: [-1.32357143  0.02839286]


In [0]:
#If you call PolynomialFeatures with the default parameter include_bias=True (or if you just omit it),
#you’ll obtain the new input array x_ with the additional leftmost column containing only ones.
#This column corresponds to the intercept. This is how the modified input array looks in this case:
x_ = PolynomialFeatures(degree=2, include_bias=True).fit_transform(x)

In [12]:
print(x_)

[[1.000e+00 5.000e+00 2.500e+01]
 [1.000e+00 1.500e+01 2.250e+02]
 [1.000e+00 2.500e+01 6.250e+02]
 [1.000e+00 3.500e+01 1.225e+03]
 [1.000e+00 4.500e+01 2.025e+03]
 [1.000e+00 5.500e+01 3.025e+03]]


In [0]:
model = LinearRegression(fit_intercept=False).fit(x_, y)

In [14]:
r_sq = model.score(x_, y)
print('coefficient of determination:', r_sq)
print('intercept:', model.intercept_)
print('coefficients:', model.coef_)

coefficient of determination: 0.8908516262498564
intercept: 0.0
coefficients: [21.37232143 -1.32357143  0.02839286]


In [15]:
# Predict response
y_pred = model.predict(x_)
print('predicted response:', y_pred, sep='\n')

predicted response:
[15.46428571  7.90714286  6.02857143  9.82857143 19.30714286 34.46428571]


In [0]:
#You can apply the identical procedure if you have several input variables. 
#You’ll have an input array with more than one column, but everything else is the same. Here is an example:
# Step 1: Import packages
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

# Step 2a: Provide data
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

# Step 2b: Transform input data
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

# Step 3: Create a model and fit it
model = LinearRegression().fit(x_, y)

# Step 4: Get results
r_sq = model.score(x_, y)
intercept, coefficients = model.intercept_, model.coef_

# Step 5: Predict
y_pred = model.predict(x_)


In [18]:
print('coefficient of determination:', r_sq)


coefficient of determination: 0.9453701449127822


In [19]:
print('intercept:', intercept)

intercept: 0.8430556452395876


In [20]:
print('coefficients:', coefficients, sep='\n')

coefficients:
[ 2.44828275  0.16160353 -0.15259677  0.47928683 -0.4641851 ]


In [21]:
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 0.54047408 11.36340283 16.07809622 15.79139    29.73858619 23.50834636
 39.05631386 41.92339046]
